apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup    
  labels:
    app: opsmx-x509
    cluster: opsmx-gate-x509
    team: opsmx
    product: engineering-productivity
    project: spin
  name: opsmx-gate-x509
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: aop
      port: 8008
      protocol: TCP
      targetPort: 8008
    - name: gate
      port: 443
      protocol: TCP
      targetPort: 8084
  selector:
    app: opsmx-x509
    cluster: opsmx-gate-x509
  sessionAffinity: None
  type: LoadBalancer
  
